### ISSUE TITLE
code run error

### ISSUE THREAD

**Issue by Polaris-ux** [Yifang-Qin/Diff-POI#1]
![image](https://github.com/Yifang-Qin/Diff-POI/assets/57226555/05fe466f-f025-4bdf-9ace-13ad1963dc5b)

Hello, when I ran the given code, the above error was reported. Is there any solution?

**Comment by Yifang-Qin** [comment]
It seems like a shape mismatch in the attention layer yet it works fine in my local environment. Could you please provide more information about the command for execution and the dataset you are using, so that I can figure out possible solutions? The shape of `geo_embs_pad` and `geo_encs` should be [64, 1024] indeed, and the `self.geo_forward` could be printed out like this:
<img width="638" alt="image" src="https://github.com/Yifang-Qin/Diff-POI/assets/91451403/f23601e7-caf6-4328-9d42-c549d62ac496">

**Comment by Yifang-Qin** [comment]
I think I have found the reason. There is a subtle difference about the implementation of 1-D convolution between the PyTorch 1.11 and previous versions. The `Conv1d` in PyTorch 1.11 used in this repo can take either $(N,C_{in},L_{in})$ or $(C_{in},L_{in})$ as the input tensor shape. If you're using some previous version of PyTorch, it may only take $(N,C_{in},L_{in})$ as acceptable input shapes. For more information you can refer to the document on `nn.Conv1d` in PyTorch [1.11](https://pytorch.org/docs/1.11/generated/torch.nn.Conv1d.html?highlight=conv1d#torch.nn.Conv1d) and [1.10](https://pytorch.org/docs/1.10/generated/torch.nn.Conv1d.html?highlight=conv1d#torch.nn.Conv1d)

To fix this issue, I would recommend you to update the PyTorch version, or adjust the shape of `geo_embs_pad` before feeding it into `self. geo_forward`.

**Comment by Polaris-ux** [comment]
> I think I have found the reason. There is a subtle difference about the implementation of 1-D convolution between the PyTorch 1.11 and previous versions. The `Conv1d` in PyTorch 1.11 used in this repo can take either (N,Cin,Lin) or (Cin,Lin) as the input tensor shape. If you're using some previous version of PyTorch, it may only take (N,Cin,Lin) as acceptable input shapes. For more information you can refer to the document on `nn.Conv1d` in PyTorch [1.11](https://pytorch.org/docs/1.11/generated/torch.nn.Conv1d.html?highlight=conv1d#torch.nn.Conv1d) and [1.10](https://pytorch.org/docs/1.10/generated/torch.nn.Conv1d.html?highlight=conv1d#torch.nn.Conv1d)
> 
> To fix this issue, I would recommend you to update the PyTorch version, or adjust the shape of `geo_embs_pad` before feeding it into `self. geo_forward`.

Thank you very much. I didn’t consider the version issue. I’ll try it tomorrow.

**Comment by Polaris-ux** [comment]
> I think I have found the reason. There is a subtle difference about the implementation of 1-D convolution between the PyTorch 1.11 and previous versions. The `Conv1d` in PyTorch 1.11 used in this repo can take either (N,Cin,Lin) or (Cin,Lin) as the input tensor shape. If you're using some previous version of PyTorch, it may only take (N,Cin,Lin) as acceptable input shapes. For more information you can refer to the document on `nn.Conv1d` in PyTorch [1.11](https://pytorch.org/docs/1.11/generated/torch.nn.Conv1d.html?highlight=conv1d#torch.nn.Conv1d) and [1.10](https://pytorch.org/docs/1.10/generated/torch.nn.Conv1d.html?highlight=conv1d#torch.nn.Conv1d)
> 
> To fix this issue, I would recommend you to update the PyTorch version, or adjust the shape of `geo_embs_pad` before feeding it into `self. geo_forward`.

Thanks again, I have successfully run
