### ISSUE TITLE
貌似代码存在数据泄露

### ISSUE THREAD

**Issue by Yukayo** [Yifang-Qin/Diff-POI#2]
你好，我在复现这项工作时发现测试集的轨迹包含了训练集和验证集出现过的POI。理论上来说，比如user 0有30个点，按8：1：1划分，前24个点产生23个轨迹作为训练集我可以理解，但是以测试集为例，测试集的轨迹不应该是从28-30组成的两条轨迹么?目前来看，代码使用测试集的形式是1-28+29，1-29+30，这样会包含训练数据欸。

**Comment by Yifang-Qin** [comment]
您好，数据泄露通常是指在训练集中掺杂进测试或验证数据，或者在测试集的输入中给模型透露标签答案，目前的模型代码并没有这个问题，因此并不存在泄露问题。实际上，我们采用的实验设置是 CTR 模型测试的常用基准方法，比如 DIN 的实现 [1] 也包含您所提到的情况。
从原理来说，序列预测模型的输入本身就是当前点击之前的全部序列，而训练/验证/测试集的划分本身就是按照时间顺序排序的，因此测试集的模型输入中包含训练集出现过的点击是正常行为。

[1] https://github.com/zhougr1993/DeepInterestNetwork/blob/master/din/build_dataset.py, line 22-29

**Comment by Yukayo** [comment]
你好，感谢你的回复。我也和其他人讨论了一下，的确不能说是数据泄露。只能说是这种方法可能会使测试的效果偏高以及不能测试模型泛化性。而且，我也发现了一些经典工作比如DeepMove, LSTPM也是这样做的。
