### ISSUE TITLE
poi_embedding问题

### ISSUE THREAD

**Issue by secortot** [Yifang-Qin/Diff-POI#3]
求问如果使用时的poi超出了训练集中的poi个数，这里的poi_embedding 该怎么做呢？

**Comment by Yifang-Qin** [comment]
在这篇工作的 setting 中，我们会默认测试时不会出现训练集中不存在的 POI（即不存在冷启动的情况）。尽管在推断时可以通过随机初始化 embedding 的方式来编码新的未训练 POI，但是这样会严重影响模型的性能。
