### ISSUE TITLE
baselines复现问题

### ISSUE THREAD

**Issue by kevin-xuan** [Yifang-Qin/Diff-POI#4]
作者，你好！非常感谢开源代码！我看到你用到了SGRec和DRAN这两个baselines，但是我在网上找不到任何一个开源代码，请问这是在某个网站开源还是你自己复现的呢？如果网上有对应代码的话，能告诉我在哪里找得到吗？如果是你复现的，能方便分享一份吗？(当然，不分享也没事的，我只是问一问)

**Comment by Yifang-Qin** [comment]
您好，这两个baseline均为作者根据论文复现的。当时负责复现论文的合作者已经毕业，他回复我说有时间的话整理好代码的pipeline并开源，届时我在此issue下附上开源链接，感谢您的关注。

**Comment by kevin-xuan** [comment]
好的好的，非常感谢作者的及时回复。
