### ISSUE TITLE
数据泄露问题

### ISSUE THREAD

**Issue by chwang0721** [Yifang-Qin/Diff-POI#5]
您好，请问这里加上exclude_mask的目的是什么呢。我个人的理解是测试时让预测的结果不能是训练集中出现过的POI，可以请教一下为什么需要这样操作吗。
https://github.com/Yifang-Qin/Diff-POI/blob/efbec20da67b1c44e843d118691b18d56560808b/code/dataset.py#L73-L76

另外，根据一般的经验，模型会更倾向于推荐已经走过的POI。这里将其余所有走过的POI加上mask，唯独对label不加mask，而这个mask在测试时是使用到的，个人认为这是数据泄露。这样在评估时除了label，所有在训练集中走过的POI的分数都很低，这会大大提升评估的指标。
https://github.com/Yifang-Qin/Diff-POI/blob/efbec20da67b1c44e843d118691b18d56560808b/code/evaluation.py#L55

如果我的理解不正确，欢迎作者批评指正，也欢迎大家一起交流这个问题。

**Comment by Yifang-Qin** [comment]
您好，感谢您对于我们工作的关注。增加 exclude_mask 确实是因为模型会倾向于推荐序列中存在的POI，在实际实验中这样的处理也能够让模型的性能提升，因此在Diff-POI以及文章中所比较的其他baseline模型的实验中都采用了同样的处理。对于label POI的特殊处理是为了防止个别在测试集中的数据ground truth被直接排除，这一特判是为了满足模型evaluation的需要。

至于您说的数据泄露问题，理论上，训练集中对于同一个user_id访问过的POI信息，属于模型在训练阶段即已知的信息，在验证/测试时利用训练集信息进行处理并不算是测试集数据泄露。另外一方面，我们采用的数据集本身是按照时间顺序进行训练/验证/测试划分的。对于同一个用户，训练中的访问在时间上也严格早于测试时出现的访问，属于是测试序列的子集，因此也不会出现时空穿越的数据泄露。

**Comment by chwang0721** [comment]
感谢您的回复。我同意您的观点训练集中对于同一个user_id访问过的POI信息不属于数据泄露，但是label POI的特殊处理确实在测试集中将label信息直接泄漏了。

您提到模型会倾向于推荐序列中存在的POI，根据数据集的分布，大多数label其实也存在于序列中，那么对这些存在的POI的预测分数都会偏高（也包括label），这时候去除其他POI只留下label对于未出现在序列中的POI是不公平的，无论是不是为了满足模型evaluation的需要。因此，并不是增加exclude_mask能够让模型的性能提升，而是对label POI的特殊处理让性能提升了。

您提到了其他baseline模型的实验中都采用了同样的处理，但是对label POI的特殊处理本身就是错误的。在错误的实验设置上进行所谓“公平”的比较是没有意义的。而且，既然是公平比较的话，为什么不采用和baseline相同的实验设置而是要自己重新设置一个呢？

**Comment by Yifang-Qin** [comment]
感谢您的观点。我们经过讨论认为尽管代码中exclude_mask确实降低了整个数据集在推荐任务上的难度，但依然能够衡量不同模型方法的POI推荐性能好坏。对于您提到的关于baseline设置的问题，文中所引用的文章大多采用了不同的数据集和实验设置，也多数并未开源，因此我们是从头搭建的Diff-POI验证环境。

在最新的commit中，我们给Diff-POI增加了 `--eval_all` 运行时选项，开启后便在验证时不进行exclude_mask处理，经过我们的初步测试，该选项会在所有数据集上降低模型表现，但是并不影响文章中关于模型性能的结论。非常感谢您对我们工作的关注和建设性意见。

**Comment by chwang0721** [comment]
非常感谢作者的回复！
