### ISSUE TITLE
实验测试

### ISSUE THREAD

**Issue by Polaris-ux** [Yifang-Qin/Diff-POI#6]
作者您好，新增加的eval_all参数设置为True后代码并不能运行，请问一下现在是完整的代码版本吗？我最近在跑实验，直接在代码中注释item_score[exclude_mask] = -1e10这行代码是否能达到相同的效果？

**Comment by Yifang-Qin** [comment]
您好，注释掉这行代码确实能达到相同的效果。或者我们在最新的 2c33e75 commit 修复了这个问题。非常感谢您的提醒

**Comment by Polaris-ux** [comment]
好的，非常感谢您的回复
